table Base_ODM2025
	lineageTag: af478c95-b92b-4fbd-8f0f-5f79fdd7187e

	column DNI
		dataType: string
		isHidden
		lineageTag: d15d0813-5047-4f36-bf81-76466ba70203
		summarizeBy: none
		sourceColumn: DNI

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NOMBRE
		dataType: string
		isHidden
		lineageTag: 05e0bb1b-eba5-453c-9bef-9749ad4716f6
		summarizeBy: none
		sourceColumn: NOMBRE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APELLIDO
		dataType: string
		isHidden
		lineageTag: 7137390e-6b6b-4d24-aaf1-c139db46168f
		summarizeBy: none
		sourceColumn: APELLIDO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: 5c639031-5de6-4189-940d-8bccf86d1045
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column 'ORIGEN ARG / EXTR'
		dataType: string
		lineageTag: 98873137-7d83-4a5b-9383-bd321c51bdfe
		summarizeBy: none
		sourceColumn: ORIGEN ARG / EXTR

		annotation SummarizationSetBy = Automatic

	column UNIVERSIDAD
		dataType: string
		lineageTag: 9971b2a7-4a2a-4267-98ee-2d48ef5184d3
		summarizeBy: none
		sourceColumn: UNIVERSIDAD

		annotation SummarizationSetBy = Automatic

	column TIPO_UNI
		dataType: string
		lineageTag: 1648227b-f183-47b8-b087-85209ac35771
		summarizeBy: none
		sourceColumn: TIPO_UNI

		annotation SummarizationSetBy = Automatic

	column PAIS_UNI
		dataType: string
		lineageTag: 03386aaa-00b0-4341-9fee-f7b293a57c4f
		dataCategory: Country
		summarizeBy: none
		sourceColumn: PAIS_UNI

		annotation SummarizationSetBy = Automatic

	column CIUDAD_UNI
		dataType: string
		lineageTag: 128dc1db-b78e-432e-b2e8-fa1b30882b20
		dataCategory: City
		summarizeBy: none
		sourceColumn: CIUDAD_UNI

		annotation SummarizationSetBy = Automatic

	column CLASE_UNI
		dataType: string
		lineageTag: ad4e9db8-b70f-4951-923a-e5e0d453c09b
		summarizeBy: none
		sourceColumn: CLASE_UNI

		annotation SummarizationSetBy = Automatic

	column ESPECIALIDAD
		dataType: string
		lineageTag: 7cc8c20a-e4c2-4537-a5c2-d8fe1f2e66b2
		summarizeBy: none
		sourceColumn: ESPECIALIDAD

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: e7e32121-98f4-47bf-bdbf-22b0dedfd362
		summarizeBy: none
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	column COMPONENTE
		dataType: int64
		formatString: 0
		lineageTag: 4a0bd1b7-f176-4706-b008-3e232e6e0360
		summarizeBy: sum
		sourceColumn: COMPONENTE

		annotation SummarizationSetBy = Automatic

	partition Base_ODM2025 = m
		mode: import
		source =
				let
				    Origen = Csv.Document(Web.Contents("https://raw.githubusercontent.com/LuisaBeccar/ODMexamen/refs/heads/main/Base_ODM2025.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Encabezados promovidos",".",",",Replacer.ReplaceText,{"PROMEDIO_CARRERA", "PUNTAJE", "PUNTAJE_CRUDO"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado",{{"ODM_GLOBAL_CRUDO", Int64.Type}, {"ODM_GLOBAL", Int64.Type}, {"ODM_CRUDO", Int64.Type}, {"ODM", Int64.Type}, {"COMPONENTE", Int64.Type}, {"NOTA_EXAMEN", Int64.Type}}),
				    #"Texto en mayúsculas" = Table.TransformColumns(#"Tipo cambiado",{{"ESPECIALIDAD", Text.Upper, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Texto en mayúsculas",{{"ESPECIALIDAD", Text.Clean, type text}}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Texto limpio","Í","I",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Á","A",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","É","E",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Ó","O",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Ú","U",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado5",{{"PROMEDIO_CARRERA", Currency.Type}, {"DIAS_DESDE_TITULO", Int64.Type}, {"FECHA_TITULO", type date}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Tipo cambiado1", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "DNI", "NOMBRE", "APELLIDO", "SEXO", "ORIGEN", "UNI", "TIPO_UNI", "PAIS_UNI", "CIUDAD_UNI", "lat", "long", "CLASE_UNI", "FECHA_TITULO", "DIAS_DESDE_TITULO", "PROMEDIO_CARRERA", "ESPECIALIDAD", "NOTA_EXAMEN", "COMPONENTE", "PUNTAJE", "PUNTAJE_CRUDO", "ODM", "ODM_CRUDO", "ODM_GLOBAL", "ODM_GLOBAL_CRUDO"}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Columnas reordenadas",{"Índice", "DNI", "NOMBRE", "APELLIDO", "SEXO", "ORIGEN", "UNI", "TIPO_UNI", "PAIS_UNI", "CIUDAD_UNI", "CLASE_UNI", "ESPECIALIDAD", "COMPONENTE"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Otras columnas quitadas",{{"ORIGEN", "ORIGEN ARG / EXTR"}}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Columnas con nombre cambiado","UNIVERSIDAD ","",Replacer.ReplaceText,{"UNI"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Valor reemplazado6",{{"UNI", "UNIVERSIDAD"}})
				in
				    #"Columnas con nombre cambiado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

