table Hechos
	lineageTag: 702f924c-8361-45ae-b83d-eb04e6e4f53d

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: ebba610c-e328-47df-a6a0-7443d4c96e72
		summarizeBy: none
		sourceColumn: Índice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: 553c0617-e2e8-48b1-af92-432dc190d1cc
		summarizeBy: sum
		sourceColumn: lat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column long
		dataType: double
		lineageTag: 0150a619-6273-4125-ac2f-21ba386f70cd
		summarizeBy: sum
		sourceColumn: long

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DIAS_DESDE_TITULO
		dataType: int64
		formatString: 0
		lineageTag: 8f67b737-6bc3-40a3-98e0-dfd54e65edf4
		summarizeBy: sum
		sourceColumn: DIAS_DESDE_TITULO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PROMEDIO_CARRERA
		dataType: double
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 66600df9-47a8-46fe-b61c-10a17101d7e7
		summarizeBy: sum
		sourceColumn: PROMEDIO_CARRERA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	column NOTA_EXAMEN
		dataType: double
		formatString: 0
		lineageTag: 4bb22048-b843-4509-b32d-2922ea7f1aa0
		summarizeBy: sum
		sourceColumn: NOTA_EXAMEN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COMPONENTE
		dataType: int64
		formatString: 0
		lineageTag: fe130ea8-56ed-4ef5-be83-a7f0cc28daf6
		summarizeBy: sum
		sourceColumn: COMPONENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PUNTAJE_FINAL
		dataType: double
		lineageTag: 7dcf4671-0dc0-464d-a3d9-9f7b4361e1f4
		summarizeBy: sum
		sourceColumn: PUNTAJE_FINAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PUNTAJE_CRUDO
		dataType: double
		lineageTag: b2ab229b-21e3-4338-84ce-e940fabd199f
		summarizeBy: sum
		sourceColumn: PUNTAJE_CRUDO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ODM_FINAL_ESP
		dataType: int64
		formatString: 0
		lineageTag: 92bb319e-7215-41ab-b245-137c5a9fde9c
		summarizeBy: sum
		sourceColumn: ODM_FINAL_ESP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ODM_CRUDO_ESP
		dataType: int64
		formatString: 0
		lineageTag: 9076f605-9235-4990-a570-43266955301a
		summarizeBy: sum
		sourceColumn: ODM_CRUDO_ESP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ODM_GLOBAL_FINAL
		dataType: int64
		formatString: 0
		lineageTag: b041c662-f37f-44a9-89b7-0b26b1d4b008
		summarizeBy: sum
		sourceColumn: ODM_GLOBAL_FINAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ODM_GLOBAL_CRUDO
		dataType: int64
		formatString: 0
		lineageTag: 48a9b9ed-96cf-4061-a351-259b157419cb
		summarizeBy: sum
		sourceColumn: ODM_GLOBAL_CRUDO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Hechos = m
		mode: import
		source =
				let
				    Origen = Csv.Document(Web.Contents("https://raw.githubusercontent.com/LuisaBeccar/ODMexamen/refs/heads/main/Base_ODM2025.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Encabezados promovidos",".",",",Replacer.ReplaceText,{"PROMEDIO_CARRERA", "PUNTAJE", "PUNTAJE_CRUDO"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado",{{"ODM_GLOBAL_CRUDO", Int64.Type}, {"ODM_GLOBAL", Int64.Type}, {"ODM_CRUDO", Int64.Type}, {"ODM", Int64.Type}, {"COMPONENTE", Int64.Type}, {"NOTA_EXAMEN", Int64.Type}}),
				    #"Texto en mayúsculas" = Table.TransformColumns(#"Tipo cambiado",{{"ESPECIALIDAD", Text.Upper, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Texto en mayúsculas",{{"ESPECIALIDAD", Text.Clean, type text}}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Texto limpio","Í","I",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Á","A",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","É","E",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Ó","O",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Ú","U",Replacer.ReplaceText,{"ESPECIALIDAD"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado5",{{"PROMEDIO_CARRERA", Currency.Type}, {"DIAS_DESDE_TITULO", Int64.Type}, {"FECHA_TITULO", type date}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Tipo cambiado1", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "DNI", "NOMBRE", "APELLIDO", "SEXO", "ORIGEN", "UNI", "TIPO_UNI", "PAIS_UNI", "CIUDAD_UNI", "lat", "long", "CLASE_UNI", "FECHA_TITULO", "DIAS_DESDE_TITULO", "PROMEDIO_CARRERA", "ESPECIALIDAD", "NOTA_EXAMEN", "COMPONENTE", "PUNTAJE", "PUNTAJE_CRUDO", "ODM", "ODM_CRUDO", "ODM_GLOBAL", "ODM_GLOBAL_CRUDO"}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Columnas reordenadas",{"Índice", "lat", "long", "DIAS_DESDE_TITULO", "PROMEDIO_CARRERA", "NOTA_EXAMEN", "COMPONENTE", "PUNTAJE", "PUNTAJE_CRUDO", "ODM", "ODM_CRUDO", "ODM_GLOBAL", "ODM_GLOBAL_CRUDO"}),
				    #"Lat y Long cambio ""."" por "",""" = Table.ReplaceValue(#"Otras columnas quitadas",".",",",Replacer.ReplaceText,{"lat", "long"}),
				    #"Tipo cambiado lat y long" = Table.TransformColumnTypes(#"Lat y Long cambio ""."" por "",""",{{"lat", type number}, {"long", type number}}),
				    #"Nota_Examen % 10" = Table.TransformColumns(#"Tipo cambiado lat y long", {{"NOTA_EXAMEN", each _ / 10, type number}}),
				    #"Tipo numero a Puntaje" = Table.TransformColumnTypes(#"Nota_Examen % 10",{{"PUNTAJE", type number}, {"PUNTAJE_CRUDO", type number}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo numero a Puntaje",{{"PUNTAJE", "PUNTAJE_FINAL"}}),
				    #"Cambio tipo a Promedio_Carrera" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"PROMEDIO_CARRERA", type number}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Cambio tipo a Promedio_Carrera",{{"ODM", "ODM_FINAL_ESP"}, {"ODM_CRUDO", "ODM_CRUDO_ESP"}, {"ODM_GLOBAL", "ODM_GLOBAL_FINAL"}})
				in
				    #"Columnas con nombre cambiado1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

