table Medidas
	lineageTag: f7856d6d-12b2-4df9-b71c-3dfb729af408

	measure Prom_Carrera = AVERAGE(Hechos[PROMEDIO_CARRERA])
		lineageTag: 0825d1c1-e9bb-4803-966a-32418fe011f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_EX = AVERAGE(Hechos[NOTA_EXAMEN])
		lineageTag: 4dfc71da-da19-4650-aed1-e07e65199ef5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_EX_F = CALCULATE([Prom_EX], Base_ODM2025[SEXO] = "F")
		lineageTag: ad7e4b52-33f3-46a8-8fd2-e1119b2c16b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_EX_M = CALCULATE([Prom_EX], Base_ODM2025[SEXO] = "M")
		lineageTag: 0af4bd0f-5471-4877-b350-b3cb890550aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Puntaje = AVERAGE(Hechos[PUNTAJE])
		lineageTag: fd08d349-83e5-4bf5-8c70-75fb71beaa20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Residentes' = DISTINCTCOUNT(Base_ODM2025[DNI])
		formatString: 0
		lineageTag: 02660bac-ebc8-4be8-9034-81148ba836c8

	column Column
		isHidden
		formatString: 0
		lineageTag: d34b718d-f15c-42ba-b30e-42f95f708290
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 5383f02fb7dd4cb397dada9cc71eec8c

